name: 'slack-notify'
description: 'Greet someone'
inputs:
  channel-id: # channel id to post message when using bot token
    description: 'Slack channel ID where message will be posted. Needed if using bot token'
    required: false
  slack-message: # message to post when using bot token
    description: 'Message to post into Slack. Needed if using bot token'
    required: false
  payload: # JSON payload to send to Slack via webhook
    description: 'JSON payload to send to Slack if webhook route. If not supplied, json from GitHub event will be sent instead'
    required: false
  payload-file-path: # path to JSON payload to send to Slack via webhook
    description: 'path to JSON payload to send to Slack if webhook route. If not supplied, json from GitHub event will be sent instead. If payload is provided, it will take preference over this field'
    required: false
  update-ts: # The timestamp of a previous message posted to update it instead of posting a new message
    description: 'The timestamp of a previous message posted. It will update the existing message instead of posting a new message'
  SLACK_TOKEN: # The timestamp of a previous message posted to update it instead of posting a new message
    description: 'The timestamp of a previous message posted. It will update the existing message instead of posting a new message'
    required: true
outputs:
  time: # id of output
    description: 'The time'
  thread_ts: # threaded timestamp on the message that was posted when using bot token
    description: 'The timestamp on the message that was posted into Slack when using bot token'
  ts: # timestamp of message posted
    description: 'The timestamp on the message that was posted into Slack when using bot token'
  channel_id: # Id of the channel. If channel name was used as input we can get ID from output for later use when updating message or posting to thread.
    description: 'The channel id of the message that was posted into Slack when using bot token'
runs:
  using: "composite"
  steps:
    - name: Send GitHub trigger using slack bot
      id: slackmessage
      uses: ./.github/actions/slack-message-send
      with:
        # The following message update step does not accept a channel name.
        # Setting a channel ID here for consistency is highly recommended.
        channel-id: "C01HLUS0S8K"
        payload: |
          {
            "text": "Build1 Generated Successfully.",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "@here \n *Build Generated Successfully.*"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.SLACK_TOKEN}}
