name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '18'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build

    # Noted For Output app/build/outputs/apk/debug/
    - name: Upload APK Debug
      id: artifactDebug
      uses: actions/upload-artifact@v4
      with:
        name: APK(s) debug generated
        path: app/build/outputs/apk/debug/
        retention-days: 1

      # Noted For Output app/build/outputs/apk/release/
    - name: Upload APK Release
      id: artifactRelease
      uses: actions/upload-artifact@v4
      with:
        name: APK(s) release generated
        path: app/build/outputs/apk/release/
        retention-days: 1