name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '18'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build

    # Noted For Output app/build/outputs/apk/debug/
    - name: Upload APK Debug
      id: artifactDebug
      uses: actions/upload-artifact@v4
      with:
        name: APK(s) debug generated
        path: app/build/outputs/apk/debug/
        retention-days: 1

      # Noted For Output app/build/outputs/apk/release/
    - name: Upload APK Release
      id: artifactRelease
      uses: actions/upload-artifact@v4
      with:
        name: APK(s) release generated
        path: app/build/outputs/apk/release/
        retention-days: 1

    - name: Send GitHub trigger payload to Slack Workflow Builder
      id: slackwebhook
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": "Danny Torrence left a 1 star review for your property.",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Danny Torrence left the following review for your property:"
                }
              },
              {
                "type": "section",
                "block_id": "section567",
                "text": {
                  "type": "mrkdwn",
                  "text": "<https://example.com|Overlook Hotel> \\n :star: \\n Doors had too many axe holes, guest in room 237 was far too rowdy, whole place felt stuck in the 1920s."
                },
                "accessory": {
                  "type": "image",
                  "image_url": "https://is5-ssl.mzstatic.com/image/thumb/Purple3/v4/d3/72/5c/d3725c8f-c642-5d69-1904-aa36e4297885/source/256x256bb.jpg",
                  "alt_text": "Haunted hotel image"
                }
              },
              {
                "type": "section",
                "block_id": "section789",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Average Rating*\\n1.0"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    - name: Send GitHub trigger using slack bot
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        # The following message update step does not accept a channel name.
        # Setting a channel ID here for consistency is highly recommended.
        channel-id: "C01HLUS0S8K"
        payload: |
          {
            "text": "Build Generated Successfully.",
            "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "ARTIFACT : ${{ steps.artifactDebug.outputs.artifact-url }}"
                  }
                }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}