name: Slack Notification 

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]

jobs:
  slack_upload_job:
    runs-on: ubuntu-latest
    name: Upload APK
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        

      - name: Send Slack Notification
        id: slack-message
        uses: mishalHexa/slack-notify
        with:
          # The following message update step does not accept a channel name.
          # Setting a channel ID here for consistency is highly recommended.
          channel-id: "C01HLUS0S8K"
          SLACK_TOKEN:  ${{ secrets.SLACK_TOKEN}}
          payload: |
            {
              "text": "Build Generated Successfully.",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "@here \n *Build Generated Successfully.*"
                  }
                }
              ]
            }
          initial_comment: "Download Release Signed APK"
          title: Release APK
          filetype: apk
          path: app/build/outputs/apk/release/app-release.apk
          channel: application-development