name: SLACK 

on:
  workflow_dispatch:

jobs:
  slack_upload_job:
    runs-on: ubuntu-latest
    name: Upload APK
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build

      - run: echo "Test file " > test.txt
      - name: Upload to slack step
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          path: app/build/outputs/apk/debug/app-debug.apk
          channel: application-development