name: SLACK 

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]

jobs:
  slack_upload_job:
    runs-on: ubuntu-latest
    name: Upload APK
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        
      - name: Send GitHub trigger using slack bot
        id: slack
        uses: ./.github/actions/slack-send
        with:
          # The following message update step does not accept a channel name.
          # Setting a channel ID here for consistency is highly recommended.
          channel-id: "C01HLUS0S8K"
          payload: |
            {
              "text": "Build Generated Successfully.",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "@here \n *Build Generated Successfully.*"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN}}

      - name: Send Debug Apk to Slack
        uses: ./.github/actions/slack-file-upload
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          initial_comment: "Download Debug APK"
          title: Debug APK
          filetype: apk
          thread_ts: ${{ steps.slack.outputs.ts }}
          path: app/build/outputs/apk/debug/app-debug.apk
          channel: application-development

      - name: Send Release Apk to Slack
        uses: ./.github/actions/slack-file-upload
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          initial_comment: "Download Release Signed APK"
          title: Release APK
          filetype: apk
          path: app/build/outputs/apk/release/app-release.apk
          thread_ts: ${{ steps.slack.outputs.ts }}
          channel: application-development